# Overview

This web app is a forum for creators who want feedback on designs for their code. They log in, create projects of varying types (structure charts, pseudocode, DFDs) and allow others to edit or 
comment on their ideas. It's a place for fun and easy collaboration when creating a program. 

# Purpose
I create better design when I am able to get consistent feedback, so I want to provide a virtual safehaven for ideas. 

{Provide a link to your YouTube demonstration.  It should be a 4-5 minute demo of the software running (starting the server and navigating through the web pages) and a walkthrough of the code.}

[Software Demo Video](https://ooo.mmhmm.app/z_sqy90I8Aj3feV2GLf5ku)

# Web Pages

*Login page - takes an email and a password and compares it with one stored within the backend. If it matches, the user is taken to the Playthink project page.
*Project page - Where users can add projects for things like pseudocode, designs for 3D printing, structure charts, etc.

# Development Environment

{Describe the tools that you used to develop the software}
VSCode, Node.js, Express

{Describe the programming language that you used and any libraries.}
I used Javascript with Node.js, vanilla Javascript, CSS, and HTML.
# Useful Websites

{Make a list of websites that you found helpful in this project}
* [Crunchify.com](https://crunchify.com/how-to-fix-refused-to-execute-script-error-its-mime-type-text-html-is-not-executable/)
* [hyenode.com](https://heynode.com/tutorial/process-user-login-form-expressjs/)
* [Programming With Mosh] (https://youtu.be/TlB_eWDSMt4?feature=shared)
* [ChatGPT] (https://chat.openai.com/)

# Future Work

{Make a list of things that you need to fix, improve, and add in the future.}
* Make the challenge page accessible
* Allow users to join groups they trust to review their ideas
* Update frontend so it looks more professional
*Create an icon for the site